# -*- coding: utf-8 -*-
"""Longitude & latitude on mentioned location generator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mCNTaQ3lOrTd7Zq4Wj954vm2P1XChn_-

## Random longitude,latitude & timestamps generation based on specified city and city's location name
"""

from geopy.geocoders import Nominatim
import random
import time

geolocator = Nominatim(user_agent="my_app")

# Define a list of 10 main places in the Kolkata City area
places = ["Victoria Memorial", "Esplanade","Indian Museum","Bara Bazar", "Sealdah", "Zakaria Street", "Taltala","Park Circus","Central","Sealdah Railway Station"]

for place in places:
    location = geolocator.geocode(f"{place}, Kolkata")
    
    if location is not None:
      latitude = location.latitude
      longitude = location.longitude

      # Generate a random latitude and longitude within a range of 0.1 degrees of the location
      random_latitude = random.uniform(latitude - 0.1, latitude + 0.1)
      random_longitude = random.uniform(longitude - 0.1, longitude + 0.1)

      timestamp = int(time.time())
      formatted_time = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(timestamp))

      print(f"Place: {place}")
      print(f"Random latitude: {random_latitude}")
      print(f"Random longitude: {random_longitude}")
      print(f"Timestamp: {formatted_time}")
      print()

    else:
      print(place)

